name: Publish docker images
on:
 pull_request:
    branches: [main]
       

jobs:

  main:
    name: Push images to docker hub

    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Push webapp to docker hub
        uses: docker/build-push-action@v1

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: leoncarrington/leonhelloworld-ruby-app
          tag_with_ref: true 
