name: Run
on:
  pull_request:
  push: { branches: main }
jobs:
  test:
    name: Run suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build docker images
      run: docker-compose build
